### ISSUE TITLE
Memory Error: 'std::bad_alloc' Aborted (core dumped)

### ISSUE THREAD

**Issue by ahmad-bashir-ai** [YuliangXiu/ECON#1]
Hi Authors,

I hope you are doing great. I am trying to run this repository my machine in the conda environment with the following specifications,

Ubuntu : 20.04
Cuda: 11.7
Python : 3.8.15
GPU: Tesla V100 16GB
I followed the step by steps instructions in the installation guide to setup the environment and there was no error during that. 
Now, when I try to run inference using this command 
`python -m apps.infer -cfg ./configs/econ.yaml -in_dir ./examples -out_dir ./results`

I got the following output with an error,

```bash
resume Normal weights from ./data/ckpt/normal.ckpt
Resume MLP weights from ./data/ckpt/ifnet.ckpt
Use IF-Nets (Implicit)+ for completion
Use PIXIE to estimate human pose and shape
Dataset Size: 1
  0%|                                                                                                                                                                          | 0/1 [00:00<?, ?it/s]INFO: Created TensorFlow Lite XNNPACK delegate for CPU.
304e9c4798a8c3967de7c74c24ef2e38:   0%|                                                                                                                                        | 0/1 [00:07<?, ?it/s]terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
Aborted (core dumped)
```

Can you please suggest the possible solution?

**Comment by YuliangXiu** [comment]
Maybe related to the [pypoisson](https://github.com/mmolero/pypoisson/issues/13), please check the `OBJ` folder to get to know which inference step caused this issue.

**Comment by ahmad-bashir-ai** [comment]
`OBJ` folder has the following files,

```
1. SMPL mesh (xxx_smpl_xx.obj)
2. SMPL params (xxx_smpl.npy)
3. d-BiNI surfaces (xxx_BNI.obj)
4. seperate face/hand mesh (xxx_hand/face.obj)
5. full shape impainted by IF-Nets+, and remeshed shape (xxx_IF_(remesh).obj)
6. sideded or occluded parts (xxx_side.obj)
````

`xxx_full.obj `is missing. Can you please tell what could be the possible reason? If you have any solution please share

**Comment by YuliangXiu** [comment]
> `OBJ` folder has the following files,
> 
> ```
> 1. SMPL mesh (xxx_smpl_xx.obj)
> 2. SMPL params (xxx_smpl.npy)
> 3. d-BiNI surfaces (xxx_BNI.obj)
> 4. seperate face/hand mesh (xxx_hand/face.obj)
> 5. full shape impainted by IF-Nets+, and remeshed shape (xxx_IF_(remesh).obj)
> 6. sideded or occluded parts (xxx_side.obj)
> ```
> 
> `xxx_full.obj `is missing. Can you please tell what could be the possible reason? If you have any solution please share

If that is the case, you probably need to reinstall `pypoisson`. Please check the link I posted in last reply.

**Comment by YuliangXiu** [comment]
> `OBJ` folder has the following files,
> 
> ```
> 1. SMPL mesh (xxx_smpl_xx.obj)
> 2. SMPL params (xxx_smpl.npy)
> 3. d-BiNI surfaces (xxx_BNI.obj)
> 4. seperate face/hand mesh (xxx_hand/face.obj)
> 5. full shape impainted by IF-Nets+, and remeshed shape (xxx_IF_(remesh).obj)
> 6. sideded or occluded parts (xxx_side.obj)
> ```
> 
> `xxx_full.obj `is missing. Can you please tell what could be the possible reason? If you have any solution please share

If that is the case, you probably need to reinstall `pypoisson`. Please check the link I posted in last reply.

**Comment by ahmad-bashir-ai** [comment]
Thanks issue resolved with installing gcc-7
