### ISSUE TITLE
Regarding the issue of mesh hand reconstruction

### ISSUE THREAD

**Issue by xx674967** [YuliangXiu/ECON#101]
Hi, thank you for releasing such an excellent work. During my testing, I have noticed that many image reconstruction results have errors in hand reconstruction around the waist, as shown in the following image. How can this issue be resolved? I look forward to your response. 

![econ_issue](https://github.com/YuliangXiu/ECON/assets/26277179/b7333426-cf16-4145-a836-958eaa03bba4)

**Comment by YuliangXiu** [comment]
It is not easy to fix such an issue, since the pocket regions are occluded in the given image. I think this will be alleviated under `use_ifnet=False` mode.

**Comment by xx674967** [comment]
> It is not easy to fix such an issue, since the pocket regions are occluded in the given image. I think this could be alleviated under `use_ifnet=False` mode.

Thank you for your response. I noticed that the TECH code has released. Can TECH handle this kind of case？ thanks ：）

**Comment by YuliangXiu** [comment]
> > It is not easy to fix such an issue, since the pocket regions are occluded in the given image. I think this could be alleviated under `use_ifnet=False` mode.
> 
> Thank you for your response. I noticed that the TECH code has released. Can TECH handle this kind of case？ thanks ：）

As there is a multi-pose training strategy in TeCH, such artifacts caused by occlusion could be reduced somehow.

**Comment by xx674967** [comment]
> > > It is not easy to fix such an issue, since the pocket regions are occluded in the given image. I think this could be alleviated under `use_ifnet=False` mode.
> > 
> > 
> > Thank you for your response. I noticed that the TECH code has released. Can TECH handle this kind of case？ thanks ：）
> 
> As there is a multi-pose training strategy in TeCH, such artifacts caused by occlusion could be reduced somehow.

Thanks, I will close this issue, have a nice day~
