### ISSUE TITLE
How to obtain a depth map for a image

### ISSUE THREAD

**Issue by wishinghao** [YuliangXiu/ECON#106]
Hello, I would like to obtain depth maps aligned with input image pixels using Econ, but I couldn't find corresponding content in the code. Is there a way to obtain clothed depth maps from d-BiNI outputs? Alternatively, are there camera parameters to project the reconstructed geometry back to the original image and obtain depth?

**Comment by YuliangXiu** [comment]
Hi @wishinghao, please check [BNI.py#L66](https://github.com/YuliangXiu/ECON/blob/master/lib/common/BNI.py#L66)
