### ISSUE TITLE
Question about diffference in benchmark & paper

### ISSUE THREAD

**Issue by glorioushonor** [YuliangXiu/ECON#107]
Good job! Why are the data in the benchmark different from the data in the paper? I am unsure which data I should use to assess whether my reproduction is successful.

**Comment by YuliangXiu** [comment]
You should evaluate on CAPE and RenderPeople, see [testing.md](https://github.com/YuliangXiu/ECON/blob/master/docs/testing.md). This is the same as original paper. Where is the difference?

**Comment by glorioushonor** [comment]
> You should evaluate on CAPE and RenderPeople, see [testing.md](https://github.com/YuliangXiu/ECON/blob/master/docs/testing.md). This is the same as original paper. Where is the difference?

Thanks for your response. It might be because I downloaded an early version of the paper. I have re-downloaded the latest version from arXiv, and the data now aligns with the testing.md. Thank you.
