### ISSUE TITLE
blender issue in Quick Start

### ISSUE THREAD

**Issue by yxsysu** [YuliangXiu/ECON#111]
Hi, thanks for your great work. I am surprised by the experimental results.
I follow the Quick Start but I encounter a error. 
```
# 1. Use HybrIK-X to estimate SMPL-X pose sequences from input video
# 2. Rig ECON's reconstruction mesh, to be compatible with SMPL-X's parametrization (-dress for dress/skirts).
# 3. Animate with SMPL-X pose sequences obtained from HybrIK-X, getting <file_name>_motion.npz
# 4. Render the frames with Blender (rgb-partial texture, normal-normal colors), and combine them to get final video

python -m apps.avatarizer -n <file_name>
python -m apps.animation -n <file_name> -m <motion_name>

# Note: to install missing python packages into Blender
# blender -b --python-expr "__import__('pip._internal')._internal.main(['install', 'moviepy'])"

wget https://download.is.tue.mpg.de/icon/econ_empty.blend
blender -b --python apps.blender_dance.py -- normal <file_name> 10 > /tmp/NULL
```

In the last step of blender, the program broke down with error ``unable to open a display''.
The problem is in line 112 of blender_dance.py:
`bpy.ops.render.render(use_viewport=True, write_still=True)`
I use blender2.82 in linux (only terminal without remote desktop), and install many packages (openGL and so forth). I confirm that I used `blender -b xxxxx`, but the error still exists. 
It is my first time to run a 3D project. I do not know how to fix this and get the video results. Could you give me some hints?

**Comment by yxsysu** [comment]
![image](https://github.com/YuliangXiu/ECON/assets/32037129/de87022f-524f-4bbf-ab38-4b26a2b9aab3)

**Comment by YuliangXiu** [comment]
Please refer to [Blender Render](https://docs.blender.org/manual/en/latest/advanced/command_line/render.html) to enable the headless rendering, or set up the blender on a machine with a display.

**Comment by chris-hndz** [comment]
Hola @yxsysu !

Sorry for my ignorance, but how can you extract the estimated SMPL-X pose sequences from input video with HybrIK-X into a file? How can you generate the SMPL-X pose sequences obtained from HybrIK-X, getting <file_name>_motion.npz ?

I managed to run HybrIK-X on a video with the command:

python scripts/demo_video_x.py --video-name examples/dance.mp4 --out-dir res_dance --save-pk --save-img

But this only generates a video from SMPL-X about the person in the video, and a folder with the image sequence of the original video, but does not generate any *.npz file.

Thanks in advance for your help! 😄

**Comment by chris-hndz** [comment]
OK, I've figures out what to do...

**1) Use the correct repository**
- Apparently the official HybrIK-X repository is incomplete, so I used [this fork](https://github.com/bananaman1983/HybrIK) and was able to export the SMPL-X pk file.

**2) Update the blender addon:**
- I followed the instructions in [this post](https://github.com/Jeff-sjtu/HybrIK/pull/170#issue-1742968266), and I was able to load and play the HybrIK-X animation in Blender, and thus export it in fbx.

I hope this will be useful to other people.

**Comment by Mhao-lxx** [comment]
Hello, blogger! Thank you for your work!

I followed your instructions and successfully exported the .pk file, but this file cannot generate animations when used with the 3D models produced by SMPL-X.

![image](https://github.com/user-attachments/assets/5cb52687-5ffc-4d61-b756-8625b761219a)


Do you know how to solve this issue? Thank you!

**Comment by yxsysu** [comment]
Sorry, I haven't used this project in a long time and can't provide assistance.
