### ISSUE TITLE
Why is the reconstruction result of my occluded images so poor?

### ISSUE THREAD

**Issue by glorioushonor** [YuliangXiu/ECON#112]
Why is the reconstruction result of my occluded images so poor?I directly used the occluded images as a reference, but the results were poor.
![image](https://github.com/YuliangXiu/ECON/assets/120625228/47235b58-bcfe-430d-8ab3-b4653dcdeff2)
![image](https://github.com/YuliangXiu/ECON/assets/120625228/b2e16bd7-49cb-4672-b56c-384636294d07)

Here are yours. How did you complete the occluded information so effectively?
![image](https://github.com/YuliangXiu/ECON/assets/120625228/aae1be14-709e-4679-99a1-85224419afc7)

**Comment by YuliangXiu** [comment]
![completion](https://private-user-images.githubusercontent.com/120625228/292757529-aae1be14-709e-4679-99a1-85224419afc7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDM2MzU4NzAsIm5iZiI6MTcwMzYzNTU3MCwicGF0aCI6Ii8xMjA2MjUyMjgvMjkyNzU3NTI5LWFhZTFiZTE0LTcwOWUtNDY3OS05OWExLTg1MjI0NDE5YWZjNy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIyN1QwMDA2MTBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yNDg3MDM1NTRkOTc2NjkyYmFhZDRmOTQ3YzBmMzZiOWY2NWE3NjQ1NzFjNGNhMDk5YTVmYzk0YTY4MTg0OThhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9._nPCUkIfy0ei4msWa24IPc0PPGRyki5HuYG9iPETcVI)
This figure is just to justify that given a partial input image plus a **good SMPL-X fits**, ECON can produce the good results.
