### ISSUE TITLE
About testing

### ISSUE THREAD

**Issue by glorioushonor** [YuliangXiu/ECON#113]
During the testing phase, the GT smpl model & GT mask are being used? Can this testing strategy reflect the true performance of the algorithm? For xample, In the inference phase, the processing of complex background images is not very effective.

**Comment by YuliangXiu** [comment]
GT SMPL-X is used during testing because our main focus is on improving the reconstruction quality of the clothed human, given the SMPL body obtained via off-the-shelf HPS methods (e.g., HybrIK-X, PIXIE, etc), rather than the accuracy of HPS (Human Pose and Shape Estimation) itself.
