### ISSUE TITLE
Username/Password Authentication Failed.

### ISSUE THREAD

**Issue by ansj11** [YuliangXiu/ECON#117]
I have register in https://icon.is.tue.mpg.de, but got Username/Password Authentication Failed. Here is my log
`Downloading SMPL...
--2024-02-29 14:20:31--  https://download.is.tue.mpg.de/download.php?domain=smpl&sfile=SMPL_python_v.1.0.0.zip&resume=1
Resolving download.is.tue.mpg.de (download.is.tue.mpg.de)... 192.124.27.139
Connecting to download.is.tue.mpg.de (download.is.tue.mpg.de)|192.124.27.139|:443... connected.
HTTP request sent, awaiting response... 401 Unauthorized

Username/Password Authentication Failed.
Archive:  data/smpl_related/models/SMPL_python_v.1.0.0.zip
  End-of-central-directory signature not found.  Either this file is not
  a zipfile, or it constitutes one disk of a multi-part archive.  In the
  latter case the central directory and zipfile comment will be found on
  the last disk(s) of this archive.
unzip:  cannot find zipfile directory in one of data/smpl_related/models/SMPL_python_v.1.0.0.zip or
        data/smpl_related/models/SMPL_python_v.1.0.0.zip.zip, and cannot find data/smpl_related/models/SMPL_python_v.1.0.0.zip.ZIP, period.
mv: cannot stat 'data/smpl_related/models/smpl/models/basicModel_f_lbs_10_207_0_v1.0.0.pkl': No such file or directory
mv: cannot stat 'data/smpl_related/models/smpl/models/basicmodel_m_lbs_10_207_0_v1.0.0.pkl': No such file or directory

Downloading SMPLify...
--2024-02-29 14:20:32--  https://download.is.tue.mpg.de/download.php?domain=smplify&sfile=mpips_smplify_public_v2.zip&resume=1
Resolving download.is.tue.mpg.de (download.is.tue.mpg.de)... 192.124.27.139
Connecting to download.is.tue.mpg.de (download.is.tue.mpg.de)|192.124.27.139|:443... connected.
HTTP request sent, awaiting response... 401 Unauthorized

Username/Password Authentication Failed.
Archive:  data/smpl_related/models/mpips_smplify_public_v2.zip
  End-of-central-directory signature not found.  Either this file is not
  a zipfile, or it constitutes one disk of a multi-part archive.  In the
  latter case the central directory and zipfile comment will be found on
  the last disk(s) of this archive.
unzip:  cannot find zipfile directory in one of data/smpl_related/models/mpips_smplify_public_v2.zip or
        data/smpl_related/models/mpips_smplify_public_v2.zip.zip, and cannot find data/smpl_related/models/mpips_smplify_public_v2.zip.ZIP, period.
mv: cannot stat 'data/smpl_related/models/smplify_public/code/models/basicModel_neutral_lbs_10_207_0_v1.0.0.pkl': No such file or directory

Downloading SMPL-X...
--2024-02-29 14:20:34--  https://download.is.tue.mpg.de/download.php?domain=smplx&sfile=models_smplx_v1_1.zip&resume=1
Resolving download.is.tue.mpg.de (download.is.tue.mpg.de)... 192.124.27.139
Connecting to download.is.tue.mpg.de (download.is.tue.mpg.de)|192.124.27.139|:443... connected.
HTTP request sent, awaiting response... 401 Unauthorized

Username/Password Authentication Failed.
Archive:  data/smpl_related/models/models_smplx_v1_1.zip
  End-of-central-directory signature not found.  Either this file is not
  a zipfile, or it constitutes one disk of a multi-part archive.  In the
  latter case the central directory and zipfile comment will be found on
  the last disk(s) of this archive.
unzip:  cannot find zipfile directory in one of data/smpl_related/models/models_smplx_v1_1.zip or
        data/smpl_related/models/models_smplx_v1_1.zip.zip, and cannot find data/smpl_related/models/models_smplx_v1_1.zip.ZIP, period.

Downloading ECON...
--2024-02-29 14:20:36--  https://download.is.tue.mpg.de/download.php?domain=icon&sfile=econ_data.zip&resume=1
Resolving download.is.tue.mpg.de (download.is.tue.mpg.de)... 192.124.27.139
Connecting to download.is.tue.mpg.de (download.is.tue.mpg.de)|192.124.27.139|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: download.php?domain=icon&sfile=econ_data.zip&resume=1 [following]
--2024-02-29 14:20:38--  https://download.is.tue.mpg.de/download.php?domain=icon&sfile=econ_data.zip&resume=1
Reusing existing connection to download.is.tue.mpg.de:443.
HTTP request sent, awaiting response... 200 OK
Length: 1489784970 (1.4G) [application/octet-stream]
Saving to: './data/econ_data.zip'

./data/econ_data.zip                                                  0%[`

**Comment by ansj11** [comment]
I have solved this problem by registering in every download link.

**Comment by YuliangXiu** [comment]
The access of all these required files could be registered via [https://icon.is.tue.mpg.de/](https://github.com/YuliangXiu/ICON/blob/master/docs/installation.md#register-at-icons-website)
