### ISSUE TITLE
Training ECON with THuman2.0.

### ISSUE THREAD

**Issue by damonchang23** [YuliangXiu/ECON#118]
First of all, thank you for sharing your great work. 

I have a questions about training. 

THuman2.0 has 525 human scans and as i know, in ICON, dataset categoried as 0-500(train), 501-505(test), 506-525(val). ECON also have a same partition to train the network? 

Thank you again.

**Comment by YuliangXiu** [comment]
Here are some related issues about training:

#40 #98 #109 #21

**Comment by YuliangXiu** [comment]
The Original ICON is trained on commercial datasets (e.g., RenderPeople), but the ICON in ECON's paper is re-trained on THuman2.0 to ease the comparison. You can refer to [testing.md](https://github.com/YuliangXiu/ECON/blob/master/docs/testing.md) to see how to benchmark the methods.
