### ISSUE TITLE
ImportError: libtorch_cuda_cu.so: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by ilhamuh97** [YuliangXiu/ECON#126]
I encountered an error while running the "Running ECON" section in Google Colab. Can someone please tell me how to fix it?

![Screenshot 2024-07-06 132604](https://github.com/YuliangXiu/ECON/assets/33753707/3f7db163-c29c-4150-ba6b-766bffca77d3)

**Comment by Bigyu-777** [comment]
I encountered the same issue. Do you have a solution?

**Comment by EricGerbers** [comment]
> I encountered the same issue. Do you have a solution?

same problem
