### ISSUE TITLE
Installing on windows

### ISSUE THREAD

**Issue by carlosedubarreto** [YuliangXiu/ECON#16]
I manage to isntall on windows and I was getting all the data ready to share, but I've got to stop to solve other issues on other projects, so, to have something avilalble, I'm sharing here the parts that I took note that might help other having problems installing ECON.

Probably the biggest problem is intalling Pythorch3d
To do that, it was actually simple, since you followed good directions, like the one in this link
https://stackoverflow.com/a/74913303/9473295

In summary, you need to, install Visual studio community 2019 with the C++ librarires,

using conda, create your venv, with python 3.8 (i think i had problems with python 3.9) 
coudl be something like this 
`conda create -n econ python=3.8`

then you activate it
`conda activate econ`

then install these
`conda install pytorch torchvision torchaudio pytorch-cuda=11.6 -c pytorch -c nvidia`
and
`conda install -c fvcore -c iopath -c conda-forge fvcore iopath`

I think you dont need to load the VS Native command tools
![image](https://user-images.githubusercontent.com/4061130/211151339-339fd1ea-c648-4ed5-bd5b-adfdd4625f00.png)

but in case you need to, it must be loaded after you activate the econ venv (with the previous packages already installed)
to do that you could, in CMD pront, execute this line of command

`%comspec% /k "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Auxiliary\Build\vcvars64.bat"`

before you press enter it will looks something like this
![image](https://user-images.githubusercontent.com/4061130/211151441-96c1574e-2505-42e2-863f-bdb49609a17f.png)

and after pressing enter, it might look like this
![image](https://user-images.githubusercontent.com/4061130/211151456-2cb8c412-642e-4e52-918e-2fc5b8817b65.png)

then get the pytorch3d package using

`git clone https://github.com/facebookresearch/pytorch3d.git`
![image](https://user-images.githubusercontent.com/4061130/211151504-ebed1efd-5b16-4fd1-81c6-21b385ba830f.png)

enter pytorch3d folder
`cd pytorch3d`
`python setup.py install`
![image](https://user-images.githubusercontent.com/4061130/211151547-9671293c-d11e-49ab-a091-912fe3cc95ba.png)

Probably you will receive this error
![image](https://user-images.githubusercontent.com/4061130/211151673-ec450f28-a6e1-4d0f-a3d9-041fb193b58a.png)

You just have to put this command:
`set DISTUTILS_USE_SDK=1`

![image](https://user-images.githubusercontent.com/4061130/211151710-b0bacb53-bed9-4136-aefd-150d722f67d7.png)

and run again 
`python setup.py install`

It will take A LOT OF TIME to finish

After it has finished, you can install the rest of python packages.
There are two other packeges you need to install inside econ folder. they are at

`D:\AI\econ\ECON\lib\common\libmesh`
and
`D:\AI\econ\ECON\lib\common\libvoxelize`

you co inside each of those two folders and type
`python setup.py install`

After executing `python setup.py install `for libmesh
![image](https://user-images.githubusercontent.com/4061130/211151861-fa27d42c-300c-4875-97b4-d2c6f2c49721.png)

After executing `python setup.py install `for libvoxelize
![image](https://user-images.githubusercontent.com/4061130/211151894-749c298b-cc26-4d58-92c2-ce41f04c04a5.png)

I think those were the most problematic part of the intalation (before it was a pain to isntall pypoisson, but luckly the amazing author manages to use another solution, so we dont have to suffer with that 😀

**Comment by nghorbani** [comment]
Kudos for sharing your experience! just out of curiosity, why not WSL?

**Comment by YuliangXiu** [comment]
> Kudos for sharing your experience! just out of curiosity, why not WSL?

Hi @nghorbani here is another introduction about how to install ECON in windows

https://github.com/YuliangXiu/ECON/blob/master/docs/installation-windows.md

**Comment by carlosedubarreto** [comment]
> Kudos for sharing your experience! just out of curiosity, why not WSL?

In my case I could not use WSL, since I was going to make an addon for blender, I had to make it fully on windows.

**Comment by EnricoBeltramo** [comment]
I add several issue compatibility to run it on windows following the official guide and py 3.8, so I installecd manually all modules using py 3.11 (maximun allowed by open3d). Here the .bat to install all packages: 

`REM vs 2019 build tool shall be installed on pc x64
REM run this inside a "x64 Native Tools Command Prompt for VS 2019" shell
REM CUDA 11.3.1 shall be installed on pc (https://developer.nvidia.com/cuda-11-3-1-download-archive)
REM and need to set the env variables of path installation here:
CALL set "CUDA_PATH=C:\CUDA\11.3.1"
CALL set "CUDA_PATH_V11_3=C:\CUDA\11.3.1"

call conda remove -n econ-py311 -y --all
call conda create -n econ-py311 -y python=3.11
call conda activate econ-py311

CALL set "PATH=%CUDA_PATH%\bin;%CUDA_PATH%\libnvvp;%PATH%"
CALL set "DISTUTILS_USE_SDK=1"

CALL pip install torch==2.5.0 torchvision==0.20.0 --index-url https://download.pytorch.org/whl/cu118
CALL pip install trimesh==4.5.3
CALL pip install torchmetrics==1.6.0
CALL pip install cupy-cuda11x==13.3.0
CALL pip install pytorch_lightning==2.4.0
CALL pip install matplotlib==3.9.3
CALL pip install open3d==0.18.0
CALL pip install scipy==1.14.1
CALL pip install einops==0.8.0
CALL pip install scikit-image==0.24.0
CALL pip install huggingface_hub==0.26.5
CALL pip install opencv-python==4.10.0.84
CALL pip install opencv-contrib-python==4.10.0.84
CALL pip install mediapipe==0.10.18
CALL pip install kornia==0.7.4
CALL pip install rembg[cpu]==2.0.60
CALL pip install Cython==3.0.11
CALL pip install joblib==1.4.2
CALL pip install boto3==1.35.76
CALL pip install termcolor==2.5.0
CALL pip install yacs==0.1.8
CALL pip install fast-simplification==0.1.7

CALL pip install git+https://github.com/facebookresearch/pytorch3d.git@V0.7.8

CALL cd lib/common/libmesh
CALL python setup.py build_ext --inplace
CALL cd ../libvoxelize
CALL python setup.py build_ext --inplace

`
. The ECON code looks run correctly with all updated package, except for two lines that needs to be sigthly changed in infer.py:

#hand_mask.index_fill_(0, torch.tensor(mano_left_vid), 1.0)
hand_mask.index_fill_(0, torch.tensor(mano_left_vid, dtype=torch.int64), 1.0)

#hand_mask.index_fill_(0, torch.tensor(mano_right_vid), 1.0)
hand_mask.index_fill_(0, torch.tensor(mano_right_vid, dtype=torch.int64), 1.0)

Let me know if works on other pc.
