### ISSUE TITLE
Splicing of head and body

### ISSUE THREAD

**Issue by JunfengLiu1** [YuliangXiu/ECON#22]
Hey,Your work is awesome!
Due to some requirements,I need to generate a human model whose head has his own texture though his body hasn't(I mean use a global texture for everyone's body).So now I've used ECON to generate a body without a head,and having a head generated by other ways.But there is a problem:How can I splice the head and the body?
This is a wired question,I know.To be honest,I'm a novice in this area and I don't know much about that.Is there any way to achieve this?

**Comment by YuliangXiu** [comment]
ECON uses [Poisson Reconstruction](https://github.com/YuliangXiu/ECON/blob/master/lib/dataset/mesh_util.py#L387) to merge body, hands and face regions. I guess it could be naturally applied on your case.
