### ISSUE TITLE
run killed

### ISSUE THREAD

**Issue by JACKYLUO1991** [YuliangXiu/ECON#23]
python -m apps.avatarizer -n <filename> shows killed in line 163.

**Comment by YuliangXiu** [comment]
> python -m apps.avatarizer -n shows killed in line 163.

Could you share the error log with me? This will help to analyze.

**Comment by JACKYLUO1991** [comment]
@YuliangXiu 应该是内存爆了，32G改为64G问题就解决了

**Comment by YuliangXiu** [comment]
> @YuliangXiu 应该是内存爆了，32G改为64G问题就解决了

Did you refer to the memory in GPU or CPU?

**Comment by JACKYLUO1991** [comment]
@YuliangXiu CPU
