### ISSUE TITLE
will this outputs can using in the game pipeline?

### ISSUE THREAD

**Issue by foocker** [YuliangXiu/ECON#26]
like animation(bone rig, skin, bvh driver, deformation),and uv map, material extract.

**Comment by YuliangXiu** [comment]
Sure, `avatarizer.py` could convert the final reconstruction mesh into an animatable avatar (bone rig, skinning weights, articulated deformation, etc), which is compatible with SMPL-X pose parameters. The UV map is still under construction.

```bash
# To animate the reconstruction with SMPL-X pose parameter
python -m apps.avatarizer -n <filename>
```
