### ISSUE TITLE
About testing data in the paper

### ISSUE THREAD

**Issue by River-Zhang** [YuliangXiu/ECON#29]
Thanks for your great work!
I was wondering if the CAPE-NFP set is in the pose.txt after I downloaded the cape data. I find that the pose.txt happens to have 100 scans' name. Did you use that for testing? Besides there is another file called test150.txt, is this also used for testing?
Thanks very much!

**Comment by River-Zhang** [comment]
I got it. Thanks very much！

**Comment by YuliangXiu** [comment]
@River-Zhang 

I updated the `pose.txt` and `loose.txt` in [testing.md](https://github.com/YuliangXiu/ECON/blob/master/docs/testing.md)

**Comment by River-Zhang** [comment]
It's very kind of you!
Best regards!
