### ISSUE TITLE
ERROR: Failed building wheel for pytorch3d

### ISSUE THREAD

**Issue by matthiev** [YuliangXiu/ECON#3]
Trying to install ECON on my workstation. Ryzen 7950X and RTX4090, Ubuntu 20.04 (WSL2 on windows 11)

Fails installing requirements with:

ERROR: Failed building wheel for pytorch3d
ValueError: Unknown CUDA arch (8.9) or GPU not supported

[error_pytorch3d.txt](https://github.com/YuliangXiu/ECON/files/10289284/error_pytorch3d.txt)

**Comment by YuliangXiu** [comment]
I double checked the [installation document](https://github.com/facebookresearch/pytorch3d/blob/main/INSTALL.md) of PyTorch3D

- If CUDA is to be used, use a version which is supported by the corresponding pytorch version and **at least version 9.2**
- If CUDA is to be used and you are building from source, the CUB library must be available. We recommend version 1.10.0

I am afraid that you have to upgrade your CUDA.
