### ISSUE TITLE
Dataset

### ISSUE THREAD

**Issue by gushengbo** [YuliangXiu/ECON#30]
Hi, I find that you train ECON and ICON with Thuman2 in Experiment. However, when I use thuman2 to train the back normal net in ICON, I got a bad result. Could you tell me how you train ICON with Thuman2? What are the training details?

**Comment by gushengbo** [comment]
@YuliangXiu  This is the result:
![微信图片_20230309170026](https://user-images.githubusercontent.com/122679046/223972070-156a08d3-8481-48c5-87a2-ca1f6efe67b4.png)
![微信图片_20230309170119](https://user-images.githubusercontent.com/122679046/223972224-831bd5fa-2364-4c7b-ae3a-50638afccaa1.png)
I can succesfully reconstruct it in front,  but not the back.

**Comment by gushengbo** [comment]
sorry, I have another question. Could I train ICON or ECON with multiple gpus?

**Comment by gushengbo** [comment]
sorry, I have another question. Could I train ICON or ECON with multiple gpus?

**Comment by YuliangXiu** [comment]
> @YuliangXiu This is the result: ![微信图片_20230309170026](https://user-images.githubusercontent.com/122679046/223972070-156a08d3-8481-48c5-87a2-ca1f6efe67b4.png) ![微信图片_20230309170119](https://user-images.githubusercontent.com/122679046/223972224-831bd5fa-2364-4c7b-ae3a-50638afccaa1.png) I can succesfully reconstruct it in front, but not the back.

This is normal, it's much harder to estimate back normal than front normal. This is because only the front RGB image is provided during the inference, so though the back normal is conditioned on SMPL-X back normal, it's almost hallucinated.

**Comment by YuliangXiu** [comment]
> sorry, I have another question. Could I train ICON or ECON with multiple gpus?

Yes, you can check [PyTorch-Lightning](https://pytorch-lightning.readthedocs.io/en/stable/accelerators/gpu_intermediate.html) for more details.

**Comment by gushengbo** [comment]
> o

Yes ,thank you. So just train back normal net with Thuman2 may get unperfect result.

**Comment by gushengbo** [comment]
> o

Yes ,thank you. So just train back normal net with Thuman2 may get unperfect result.
