### ISSUE TITLE
About positional embedding

### ISSUE THREAD

**Issue by Mors20** [YuliangXiu/ECON#31]
Hi, thanks for your excellent work. As the paper saying,  “the positional embedding (N freqs = 6) of query points is concatenated with multi-scale deep features to account for high-frequency details. '' I don't find positional embedding part in the Code. So I would like to know where this part of code is?
Thanks!

**Comment by YuliangXiu** [comment]
To save GPU memory, I finally removed the PE module from Li et al.[1] but forgot to update the arXiv's appendix. Will correct it in the next version of arXiv, thanks so much for pointing out. 

If you want to have a try, you could find it from the source code in [sharp2022](https://github.com/BoSmallEar/sharp2022/blob/main/src/models/ifnet_texture_pos_encoding.py#L59).

[1] Li L, Liu Z, Ren W, et al. 3D textured shape recovery with learned geometric priors[J]. arXiv preprint arXiv:2209.03254, 2022.

**Comment by Mors20** [comment]
Thanks very much
