### ISSUE TITLE
about testing

### ISSUE THREAD

**Issue by River-Zhang** [YuliangXiu/ECON#32]
Hi, I was wondering if you could provide the testing and training code so that we can test and train on other datasets!
Thanks very much!

**Comment by YuliangXiu** [comment]
- testing code: it's quite messy, I will release the `benchmark.py` for evaluation after cleaning
- training code: please refer to #21 

I highly recommend using ECON_EX for testing or evaluation, which is optimization-based and requires no training process. And the normal and SMPL-X estimators are borrowed from off-the-shelf approaches.

**Comment by River-Zhang** [comment]
Thanks very much！
By the way, I also want to ask something about the 3D  results' images in the paper. Could you please tell me what rendering tools did you use to turn the mesh into such nice pictures? 
![1679145827333](https://user-images.githubusercontent.com/60051616/226108934-efda431e-695f-4c6d-b871-dc68dbc1bbf1.png)

**Comment by YuliangXiu** [comment]
Very simple

Meshlab (phong.gdb rendering -- save snapshot) + Google Drawing (Format options -- Recolor)

**Comment by YuliangXiu** [comment]
@River-Zhang Testing code is ready to use, please check [testing.md](https://github.com/YuliangXiu/ECON/blob/master/docs/testing.md) for more details

**Comment by River-Zhang** [comment]
Copy that！
Thanks very much!
