### ISSUE TITLE
ECON CoLab fails in step 7

### ISSUE THREAD

**Issue by jnevin** [YuliangXiu/ECON#34]
![image](https://user-images.githubusercontent.com/466297/225824854-4fd53f84-134e-4b04-bc8f-fd0724bb0d01.png)

https://colab.research.google.com/drive/1YRgwoRCZIrSB2e7auEWFyG10Xzjbrbno#scrollTo=9B9BSScMX2y0&line=1&uniqifier=1

All 6 prior steps executed correctly without issue.

**Comment by jnevin** [comment]
SORRY - IT'S STEP 8 THAT FAILS.

I retried the next day, same failure to build for voxelize-cuda:

![image](https://user-images.githubusercontent.com/466297/226072781-25e73f64-9b27-4441-ae0e-8ce9e1836046.png)

**Comment by YuliangXiu** [comment]
I just updated the code to remove the dependency on `voxelize-cuda`, you can have another try

**Comment by jnevin** [comment]
Fails with different error now in Step 8:
![image](https://user-images.githubusercontent.com/466297/226222905-1d017573-da98-4962-ba2a-3272ea79eeef.png)

Thanks investigating YuliangXiu

**Comment by 1766685212** [comment]
我刚刚试了，也是同样的错误

**Comment by 1766685212** [comment]
![屏幕截图_20230320_104016](https://user-images.githubusercontent.com/128337299/226234458-c41fc08a-6acd-4073-9f70-77e909ddab99.png)

**Comment by YuliangXiu** [comment]
@jnevin @1766685212 

It does take some effort to install PyTorch3D successfully, but I finally make it and create the wheel file.

Now you can have another try on Colab, and it will reduce the installation time from 20min to 2min.

**Comment by jnevin** [comment]
hi @YuliangXiu tried again and final mesh generation fails. it complains about PyTorch3D being unavailable:
![image](https://user-images.githubusercontent.com/466297/226711254-e5c8054e-05b9-44c2-bacc-b1c66f0bc397.png)

Will attempt again...

**Comment by jnevin** [comment]
^^ ModuleNotFoundError: No module named 'pytorch3d'

**Comment by jnevin** [comment]
@YuliangXiu the PyTorch3D wheel DOES seem to succeed. The final creation of the result FAILS however when executing the Running ECON step.

Here is the PyTorch3d wheel success:
![image](https://user-images.githubusercontent.com/466297/226718768-1b1b7ed2-7bac-42db-b14e-7198f3322ab0.png)

But the same error as above is thrown with ModuleNotFoundError.

**Comment by YuliangXiu** [comment]
![image](https://user-images.githubusercontent.com/7944350/226770388-a27ba94b-0d39-47c1-8c55-ed6b486069d7.png)
But this works for me, have you already set the "GPU" as follows?
![image](https://user-images.githubusercontent.com/7944350/226770491-075ca29c-1c0b-4b56-9a96-ead9f9afcf4e.png)

**Comment by jnevin** [comment]
<img width="1199" alt="image" src="https://user-images.githubusercontent.com/466297/226776395-c1659cee-1572-418a-97b5-06d4ebd363dc.png">

**Comment by jnevin** [comment]
@YuliangXiu Notebook still fails in final step, although now it is complaining about Cuda device. 

See the full flow of my notebook execution -- note that Nvida GPU matches yours.

<img width="1199" alt="image" src="https://user-images.githubusercontent.com/466297/226776853-fe9b04eb-381b-432a-a4e8-ececbb33225c.png">

<img width="463" alt="image" src="https://user-images.githubusercontent.com/466297/226776986-2283add7-9d9a-44d3-9cdb-67c7773c50b0.png">

<img width="1141" alt="image" src="https://user-images.githubusercontent.com/466297/226777032-d390e2b9-872a-4707-908e-847f0d4df63c.png">

<img width="1203" alt="image" src="https://user-images.githubusercontent.com/466297/226777123-bf14152d-741b-4d58-8ebf-273d16b5eb01.png">

<img width="1028" alt="image" src="https://user-images.githubusercontent.com/466297/226777165-035142ec-661b-4031-a833-5b0fc758059d.png">

<img width="1196" alt="image" src="https://user-images.githubusercontent.com/466297/226777189-d2f3e5f8-649b-4410-8264-d2ddbc5a03b1.png">

<img width="1207" alt="image" src="https://user-images.githubusercontent.com/466297/226777224-d7043dcb-bac3-4460-9efb-175bc5bf33ff.png">

<img width="1199" alt="image" src="https://user-images.githubusercontent.com/466297/226777254-ba55ecec-be61-4db8-92db-9ae8211c55a8.png">

<img width="1186" alt="image" src="https://user-images.githubusercontent.com/466297/226777278-f4b7c58c-5b9d-4b96-9c09-6538f2cc0b00.png">

<img width="1213" alt="image" src="https://user-images.githubusercontent.com/466297/226777290-0cb44da5-f563-4231-8746-f9d5d38e8e4b.png">

<img width="1240" alt="image" src="https://user-images.githubusercontent.com/466297/226777307-6632f243-4e89-4238-a693-4ac20c548cbd.png">

<img width="1211" alt="image" src="https://user-images.githubusercontent.com/466297/226777322-5ca9f246-f549-4d0d-81e2-0f1ef5895fe9.png">

<img width="1196" alt="image" src="https://user-images.githubusercontent.com/466297/226777342-35a4c53f-bbc6-4b74-a05c-04506f37332e.png">

<img width="1193" alt="image" src="https://user-images.githubusercontent.com/466297/226777356-8dc25744-cacf-43fb-85bc-695ed8293459.png">

<img width="1209" alt="image" src="https://user-images.githubusercontent.com/466297/226777385-5139c89f-7850-4e06-b888-33e1070d6642.png">

**Comment by jnevin** [comment]
@YuliangXiu ^^ note that i am on "free" CoLab" account and not paying for Premium Colab service. So "standard GPU" only for me.

**Comment by YuliangXiu** [comment]
The PyTorch3D package is rwally annoying. I will check it later after flight landing.

**Comment by YuliangXiu** [comment]
@jnevin 

<img width="890" alt="image" src="https://user-images.githubusercontent.com/7944350/227269875-319c41ec-2f34-4e0a-846e-b34dbee23bda.png">

Finally!

**Comment by jnevin** [comment]
Will test and verify. Thank you for working so hard to resolve this.

**Comment by jnevin** [comment]
@YuliangXiu success in running the example!
