### ISSUE TITLE
About complicated hand reconstruction

### ISSUE THREAD

**Issue by Apeng-Rzp** [YuliangXiu/ECON#37]
Amazing result. I want to input the hand image into the neural network and get the hand in obj/mesh format. Then I want to fit into the result of Econ, what should I do? Can I get the result by changing the hand replacement in the infer.py file?

**Comment by YuliangXiu** [comment]
Maybe you can edit in image space, crop and replace hand regions, and then use ECON for reconstruction.

Or you can check [infer.py#L585](https://github.com/YuliangXiu/ECON/blob/master/apps/infer.py#L585), here we separate the hands from SMPL-X, and combine it with body using poisson.
