### ISSUE TITLE
about  test   more  person   output    .obj

### ISSUE THREAD

**Issue by zhanghongyong123456** [YuliangXiu/ECON#38]
I did not find the obj file of multiple people in the obj folder, where can I get it?
![image](https://user-images.githubusercontent.com/48466610/229054240-8478b0df-c207-419d-a044-680688eae364.png)

**Comment by YuliangXiu** [comment]
`xx_full.obj` is the final **per-person** reconstruction mesh, there is no single obj which contains all the humans.
