### ISSUE TITLE
段错误

### ISSUE THREAD

**Issue by JunfengLiu1** [YuliangXiu/ECON#39]
我遇到了这样的报错：
![1](https://user-images.githubusercontent.com/122666174/229261059-0d1f8d4e-6998-46e3-a6df-031e2ce37ed5.png)
并且在产生的文件中只有1_smpl_00.npy和1_smpl_00.obj文件，如何解决呢

**Comment by JunfengLiu1** [comment]
但是当我把use_ifnet改成false时，就正常了

**Comment by YuliangXiu** [comment]
ECON提供了两种几何补全的策略，一种是数据驱动的`IF-Net+`，一种是纯优化方法（不需要任何训练数据），从最终的结果来看，后者效果更好速度也更快一些，如果`use_ifnet=True`出现报错，需要具体debug来确定问题，segmentation fault有很多可能的原因，但这里，我更推荐直接用`use_ifnet=False`就好。

**Comment by Connaught0** [comment]
![image](https://user-images.githubusercontent.com/37895469/236774445-97f3ee7f-baa4-419d-be32-b5da1d200d83.png)
![image](https://user-images.githubusercontent.com/37895469/236774573-814fedfb-99c6-44ee-8006-32552fa0f269.png)
我也遇到了同样的问题，大概定位了一下问题发生在了如下的代码，并且是内存溢出，是否是pretrain的ifnet出现了问题，我是否需要自己来训练一个新的网络。
