### ISSUE TITLE
Rendering Issue

### ISSUE THREAD

**Issue by Phil0419** [YuliangXiu/ECON#42]
The image of geometry in your paper looks smooth and clean. Can you share the method of rendering and its detailed parameters?
I have tried rendering with meshlab but my results seems transparent in a lot regions of human body and doesn't looks great, as I showed in the second picture.
Thanks for your help!
![image](https://user-images.githubusercontent.com/84560533/230888793-2bdc98ea-38da-4952-8f9b-9f5bf413f8e5.png)
![image](https://user-images.githubusercontent.com/84560533/230890025-12113257-e25d-472b-a14d-307a5b9af45b.png)

**Comment by YuliangXiu** [comment]
Please check this reply, https://github.com/YuliangXiu/ECON/issues/32#issuecomment-1474855939
