### ISSUE TITLE
CoLab Failure / Crash Step 10

### ISSUE THREAD

**Issue by jnevin** [YuliangXiu/ECON#43]
Hey YuliangXiu

This new issue just raised on Step 10 of ECON Colab:

![image](https://user-images.githubusercontent.com/466297/231022552-6a922e5b-8922-4e15-9890-25378bc46a37.png)

**Comment by jnevin** [comment]
@YuliangXiu  - i repeated prior Step 9 just to make sure, and still had above failure in Step 10. Looks like an issue with the ext_modules option settings

**Comment by kwan3854** [comment]
I experienced the same error message as you did. I found out that the issue started occurring after yesterday's GitHub commit. You can resolve the problem by using the previous commit version. Modify the content of the 5th cell in Colab as follows:
```bash
# Clone the repository
!git clone https://github.com/YuliangXiu/ECON/
%cd ECON
!git checkout f93dcd94ff06abcc71a64379d9d26dd1642f495f
```

**Comment by YuliangXiu** [comment]
Fixed.

This code generates the error:

```python
from Cython.Build import cythonize
from setuptools import find_packages, setup
```

This code does not generate the error:

```python
from setuptools import find_packages, setup
from Cython.Build import cythonize
```

[1] https://stackoverflow.com/questions/21594925/error-each-element-of-ext-modules-option-must-be-an-extension-instance-or-2-t

**Comment by jnevin** [comment]
@YuliangXiu wow - good catch! thanks I will re-test.
