### ISSUE TITLE
Texture issues with avatarizer.py - jagged black seams

### ISSUE THREAD

**Issue by kwan3854** [YuliangXiu/ECON#45]
Hello,

I have recently used ECON's avatarizer.py to generate a 3D character model in T-pose. I noticed that the resulting texture appears to have jagged black seams, resembling gaps in a puzzle.

I would appreciate any guidance or suggestions to resolve this issue. 
![tom_cruise](https://user-images.githubusercontent.com/30712687/231767384-e67a24dd-e2df-4734-9c43-2e4ead7821bb.jpg)

<img width="1792" alt="black_semas_problem_tom_cruise" src="https://user-images.githubusercontent.com/30712687/231767348-363a4909-477d-4295-93de-b6741ad6d9cd.png">

**Comment by YuliangXiu** [comment]
The `xx_full.obj` has better well-aligned texture, and w/o black seams. You can check it. 

The results generated from `Avatarizer.py` are not perfectly aligned with original reconstruction (I am still looking into this bug), and the black seams mainly come from the imperfect `xatlas` UV mapping.

**Comment by YuliangXiu** [comment]
@kwan3854 Now the alignment is prefect with the [commit#48](https://github.com/YuliangXiu/ECON/commit/d68130fca297c3027612d99f7275e0af31ae4333)

**Comment by YuliangXiu** [comment]
We recently released a new work, TeCH. Given a single image, TeCH could produce a **full textured avatar** with both intricate geometric details and consistent high-quality texture.

<div align="center">
    <video autoplay loop muted src="https://github.com/huangyangyi/TeCH/assets/7944350/f8fc55ed-9cbe-4b5f-bd1d-237396360713" type=video/mp4>
    </video>
  </div>

Homepage: https://huangyangyi.github.io/TeCH/
