### ISSUE TITLE
Something strange in the expoting obj file

### ISSUE THREAD

**Issue by Yuanhong200727** [YuliangXiu/ECON#5]
Thank you so much for your awesome work,sir!
But something strange happen in the exporting obj file like this:
![img](https://user-images.githubusercontent.com/117512740/209344855-029e72f5-8acc-43a9-8a03-2c14e1eb48ae.png)

The input  is a standard T-pose photo,but the output is skew(including the arms and legs).How could it happen?Maybe my picture is not so suitable for the model to predict. So are there certain requirements or something to pay attention to for the input images?
Thank you again!

**Comment by Marianoeli** [comment]
I also encountered this problem, is there anything need to pay attention to?

**Comment by YuliangXiu** [comment]
I have discussed this failure case in ECON's paper. This issue mainly comes from off-the-shelf HPS (Human Pose & Shape Estimation), which were trained on pseudo 3D ground truth, have bias towards mean pose, or to say, the bent legs / arms. Apart from alerting HPS approaches (ECON supports PIXIE and PyMAF-X), another workaround is to re-posed the reconstruction with pre-defined SMPL-X pose parameters as follows:

```bash

# To animate the reconstruction with SMPL-X pose parameters
python -m apps.avatarizer -n {filename}
```

For standard T-pose, you just need to set all pose parameters as zero as [body_models.py#L1244](https://github.com/YuliangXiu/ECON/blob/master/lib/smplx/body_models.py#L1244)

**Comment by Yuanhong200727** [comment]
Thank you so much,I will try it!

**Comment by Yuanhong200727** [comment]
@YuliangXiu For some reason,I don't want to use the visible face from SMPL-X.But when I set ["hand"] or [] in config/econ.yaml and ran `python -m apps.avatarizer -n {filename}` (I had changed smpl_out_lst[2] to smpl_out_lst[0]),the output file {filename}_econ_pose.obj was wrong.It was only about 400KB and I coudn't open it.But the {filename}_econ_da.obj was normal.
Is this a normal phenomenon?How can I solve the problem.Is there any way that after running avatarizer.py,my hands are from SMPL-X and my face was actually mine.Thanks!

**Comment by YuliangXiu** [comment]
> @YuliangXiu For some reason,I don't want to use the visible face from SMPL-X.But when I set ["hand"] or [] in config/econ.yaml and ran `python -m apps.avatarizer -n {filename}` (I had changed smpl_out_lst[2] to smpl_out_lst[0]),the output file {filename}_econ_pose.obj was wrong.It was only about 400KB and I coudn't open it.But the {filename}_econ_da.obj was normal. Is this a normal phenomenon?How can I solve the problem.Is there any way that after running avatarizer.py,my hands are from SMPL-X and my face is actually mine.Thanks!

I just updated the code to fix this bug.

**Comment by YuliangXiu** [comment]
@Marianoeli @Yuanhong-Zheng 

The issue of bending legs get resolved finally, please check out [tricks.md/bending-legs](https://github.com/YuliangXiu/ECON/blob/master/docs/tricks.md#bending-legs).
