### ISSUE TITLE
TEXTure Feature: Texture Generation Not Based on Original Input Image

### ISSUE THREAD

**Issue by kwan3854** [YuliangXiu/ECON#52]
I recently tried out the newly added TEXTure feature, expecting it to complete the texture based on the input image as shown in the [TEXTure Paper](https://texturepaper.github.io/TEXTurePaper/). However, the code from [YuliangXiu/TEXTure](https://github.com/YuliangXiu/TEXTure) seems to be determined by the prompt in the TEXTure/configs/text_guided/avatar.yaml file, specifically on line 5: text: "A gorgeously composed, high-resolution photograph of a 30 years old man wearing red shirt, blue pants, brown shoes, {} view to the camera".

~~Is it currently impossible to generate a texture that matches the original image provided as input to ECON?~~
I've come to realize that this issue stems from the original https://github.com/TEXTurePaper/TEXTurePaper code not providing this functionality yet. Are there any plans to implement this feature directly in the future, or to integrate a similar functionality using another open-source texture generator?

**Comment by YuliangXiu** [comment]
We recently released a new work, TeCH. Given a single image, TeCH could produce a **full textured avatar** with both intricate geometric details and consistent high-quality texture.

<div align="center">
    <video autoplay loop muted src="https://github.com/huangyangyi/TeCH/assets/7944350/f8fc55ed-9cbe-4b5f-bd1d-237396360713" type=video/mp4>
    </video>
  </div>

Homepage: https://huangyangyi.github.io/TeCH/
