### ISSUE TITLE
Evaluate on THuman dataset

### ISSUE THREAD

**Issue by River-Zhang** [YuliangXiu/ECON#53]
If I want to test on THuman, what scale should I set? 
Thanks very much!!

**Comment by River-Zhang** [comment]
Besides, when testing normal differences, I wonder why this equation is multiplied by 4? Is it because there are four views being tested? 
![image](https://user-images.githubusercontent.com/60051616/234162467-1ba3db15-31e3-4c2e-bd6f-a7be827d07e4.png)

**Comment by YuliangXiu** [comment]
> Besides, when testing normal differences, I wonder why this equation is multiplied by 4? Is it because there are four views being tested? ![image](https://user-images.githubusercontent.com/60051616/234162467-1ba3db15-31e3-4c2e-bd6f-a7be827d07e4.png)

Yes

**Comment by YuliangXiu** [comment]
> If I want to test on THuman, what scale should I set? Thanks very much!!

If it's THuman2.0, the scale should be 100.0 as [train/icon-filter.yaml#L28](https://github.com/YuliangXiu/ICON/blob/master/configs/train/icon-filter.yaml#L28)

**Comment by River-Zhang** [comment]
Thanks very much!
