### ISSUE TITLE
How can i get normal infromation?

### ISSUE THREAD

**Issue by qhur135** [YuliangXiu/ECON#55]
Hello,

Firstly, I would like to thank you for sharing your code on Github. It's been very helpful.

I was wondering if you could provide some guidance on how to obtain the normal vector information for the image using your code? Any help or suggestions would be greatly appreciated.

Thank you.

**Comment by YuliangXiu** [comment]
You can check the `./results/econ/png` folder, the normal images are saved over there.

**Comment by qhur135** [comment]
Thank you so much!!
