### ISSUE TITLE
IndexError: index_fill_(): Expected dtype int64 for index.

### ISSUE THREAD

**Issue by mister-raupe** [YuliangXiu/ECON#58]
Hello, thank you for providing the code and the installation instructions! 
Unfortunately I have run into this problem when I try to run the Demo. I am really unexperienced and can't resolve the issue myself. So any help is appreciated :)

Windows 11
Cuda 11.6
Anaconda

the full error message:

![image](https://user-images.githubusercontent.com/63673389/236697962-94ad474e-e264-4f66-92b1-cdbfba845486.png)

**Comment by vrai17** [comment]
same

**Comment by LSpych** [comment]
Adding 'dtype=torch.int64' worked for me, as in this example from line 95 of mesh_util.py:

self.smpl_mano_vertex_mask = torch.zeros(self.smpl_verts.shape[0],).index_fill_(0,torch.tensor(self.smpl_mano_vid, **dtype=torch.int64**), 1.0

**Comment by YuliangXiu** [comment]
@LSpych Thanks, pull request for this fix is welcome, and you will be listed as contributor as well.

**Comment by 2601705041** [comment]
same problem

**Comment by 2601705041** [comment]
> Adding 'dtype=torch.int64' worked for me, as in this example from line 95 of mesh_util.py:
> 
> self.smpl_mano_vertex_mask = torch.zeros(self.smpl_verts.shape[0],).index_fill_(0,torch.tensor(self.smpl_mano_vid, **dtype=torch.int64**), 1.0
it works for me,but then i type 'python -m apps.infer -cfg ./configs/econ.yaml -in_dir ./examples -out_dir ./results' there is nothing happened

**Comment by alexwang2013** [comment]
thanks. this works for me on windows.

my env is the following:
windows 10
CUDA 12.1
MiniConda
