### ISSUE TITLE
Is there any convenient way that I can color my own generated character model?

### ISSUE THREAD

**Issue by Marianoeli** [YuliangXiu/ECON#6]
Thanks for your apealling work,sir.The character model being generated has beyond my preliminary imagination,better than other models I 've used before.It certainly will be way more better if I am capable of  coloring it.
**So I wanna ask that is there any convenient way that I can color my own generated character model or get the model texture and apply to it?**I would be very grateful if you could answer.Thanks

**Comment by Yuanhong200727** [comment]
I met the same question.Can I color the exporting model according to the raw photo or picture?

**Comment by YuliangXiu** [comment]
I updated the [infer.py#L532](https://github.com/YuliangXiu/ECON/blob/master/apps/infer.py#L532) with `query_color` from original image, but this could only provide front-side texture, as for the back-side colors, I set normal color.

PIFu uses another network to predict back-side colors from front-side colors, but always lead to blurry and unrealistic back-side textures. I am thinking about using the `depth2img` feature in Stable Diffusion to inpaint the full colors. But this is still under construction, will let you know once finished. I will leave this issue open until solved completely.

**Comment by Yuanhong200727** [comment]
Thank you so much,sir.
But when I ran the new demo in infer.py,an error occured when rendering the final mesh:
![error](https://user-images.githubusercontent.com/117512740/209523053-5caf7fce-22c6-4168-a2e3-3c3eb715e61c.jpg)
The error occured both in my own photo and the initial photo given.

**Comment by YuliangXiu** [comment]
> Thank you so much,sir. But when I ran the new demo in infer.py,an error occured when rendering the final mesh: ![error](https://user-images.githubusercontent.com/117512740/209523053-5caf7fce-22c6-4168-a2e3-3c3eb715e61c.jpg) The error occured both in my own photo and the initial photo given.

I have updated the code with `torch.tensor` wrapper. The `query_color` is almost the same as [ICON's query_color](https://github.com/YuliangXiu/ICON/blob/master/apps/infer.py#L501).

**Comment by Yuanhong200727** [comment]
Is there something wrong with the exported xx_0_full.obj,sir?The obj file did change(4.4MB now),but in my blender,the object had no texture,which was the same in 3D viewer.
![blender](https://user-images.githubusercontent.com/117512740/209766939-2474de6f-4111-4ec8-b987-db2beeadb009.jpg)

**Comment by YuliangXiu** [comment]
@Marianoeli @Yuanhong200727 

I have a try on Blender's add-on [Dream-Textures](https://github.com/carson-katri/dream-textures) under depth2img mode, and it gives me some promising textures.

**Front Prompt**: asian man dressed in red blazer, blue jeans and brown boots
**Back Prompt**: asian man dressed in red blazer, blue jeans and brown boots, and back to the camera

|Front|Back|
|:---:|:---:|
|![image](https://user-images.githubusercontent.com/7944350/210227940-ea94809d-29fb-4635-a266-a3cc04e9ff59.png)|![image](https://user-images.githubusercontent.com/7944350/210227956-efb0c5ca-330d-45e0-ab1c-4e0a740b7a6d.png)|

Apparently, the 1) face/hands 2) front+back consistency could be improved further, but I think this is a promising approach to synthesize any texture you want.

**Comment by YuliangXiu** [comment]
Here is a highly related paper which shares the same insight but with much more promising results

https://texturepaper.github.io/TEXTurePaper/

**Comment by Yuanhong200727** [comment]
> Here is a highly related paper which shares the same insight but with much more promising results
> 
> https://texturepaper.github.io/TEXTurePaper/

Awesome work！Thanks for your sharing

**Comment by YuliangXiu** [comment]
@Marianoeli @Yuanhong200727 

Please check https://github.com/YuliangXiu/ECON#demo to texturify the ECON reconstruction with full texture.

**Comment by YuliangXiu** [comment]
@Marianoeli @Yuanhong200727 

We recently released a new work, TeCH. Given a single image, TeCH could produce a **full textured avatar** with both intricate geometric details and consistent high-quality texture.

<div align="center">
    <video autoplay loop muted src="https://github.com/huangyangyi/TeCH/assets/7944350/f8fc55ed-9cbe-4b5f-bd1d-237396360713" type=video/mp4>
    </video>
  </div>

Homepage: https://huangyangyi.github.io/TeCH/
