### ISSUE TITLE
the results of using infer.py is different from using benchmark.py

### ISSUE THREAD

**Issue by Holmes-Alan** [YuliangXiu/ECON#66]
For the same example from CAPE dataset, using infer.py code gets different 3D results to benchmark.py. Could you please tell me what the problem is?
![Picture1](https://github.com/YuliangXiu/ECON/assets/15608099/3abebe78-9c86-43d5-b2f6-5391b8fff830)

**Comment by YuliangXiu** [comment]
`benchmark.py` uses gt SMPL as 3D body prior, while `infer.py` uses SMPL-X predicted by PIXIE instead.
