### ISSUE TITLE
about adding texture

### ISSUE THREAD

**Issue by ChangYaQi** [YuliangXiu/ECON#67]
ECON outputs only have front-view color, if I provide consistent backview 2d image of the model, how can I apply it on .
Acutually, I find the code first find the front view of model, then apply vertex_color from source image
I don't know whtether my understanind is correct or not? 
```python
            if cfg.bni.texture_src == 'image':
                final_colors = query_color(
                    # verts, gace, image
                    torch.tensor(final_mesh.vertices).float(),
                    torch.tensor(final_mesh.faces).long(),
                    
                    in_tensor["image"][idx:idx + 1],     #idx
                    device=device,
                )
                final_mesh.visual.vertex_colors = final_colors
                final_mesh.export(final_path)

```

**Comment by ChangYaQi** [comment]
thanks a lot !!

**Comment by YuliangXiu** [comment]
If an appropriately aligned back image is available, it is possible to replace the existing back normal map (which was predicted from the front image) with a more detailed normal map (generated from the back image). This substitution can significantly improve the quality of the reconstruction.

If works, a pull request would be appreciated. 😃

**Comment by yuedajiong** [comment]
I have implemented:  fill backward texture from backward image.
may I submit these code?

**Comment by ChangYaQi** [comment]
> I have implemented: fill backward texture from backward image. may I submit these code?
> 
> [000_0_full.obj.zip](https://github.com/YuliangXiu/ECON/files/11862619/000_0_full.obj.zip)
I just can't add textire to obj at same time, because the color will be overwrite by the normal color , could you please share the code

**Comment by tomorrow1238** [comment]
> > I have implemented: fill backward texture from backward image. may I submit these code?
> > [000_0_full.obj.zip](https://github.com/YuliangXiu/ECON/files/11862619/000_0_full.obj.zip)
> 
> I just can't add textire to obj at same time, because the color will be overwrite by the normal color , could you please share the code. By the way, my way to get consistent backward image is to generate image is: using the 2d projection of the ECON output obj, and use canny+depth model with stable diffsuion.
> 
> HERE IS EXAMPLE
> 
> ![图片1](https://user-images.githubusercontent.com/52132819/248639978-67584eb2-ef67-48b8-a78d-4d6a6556738f.png)

May I ask if the method used here to obtain consistent backward images is an open source tool on the internet. Could you please share it with me

**Comment by ChangYaQi** [comment]
> > > I have implemented: fill backward texture from backward image. may I submit these code?
> > > [000_0_full.obj.zip](https://github.com/YuliangXiu/ECON/files/11862619/000_0_full.obj.zip)
> > 
> > 
> > I just can't add textire to obj at same time, because the color will be overwrite by the normal color , could you please share the code. By the way, my way to get consistent backward image is to generate image is: using the 2d projection of the ECON output obj, and use canny+depth model with stable diffsuion.
> > HERE IS EXAMPLE
> > ![图片1](https://user-images.githubusercontent.com/52132819/248639978-67584eb2-ef67-48b8-a78d-4d6a6556738f.png)
> 
> May I ask if the method used here to obtain consistent backward images is an open source tool on the internet. Could you please share it with me

I just write a gradio demo which can let the reconstruction and texture genrateation work in just one web page. The main tworkflow is to get the backend projection of recon obj, then use this picture as the input of controlnet.

**Comment by YuliangXiu** [comment]
@ChangYaQi @yuedajiong 

We recently released a new work, TeCH. Given a single image, TeCH could produce a **full textured avatar** with both intricate geometric details and consistent high-quality texture.

<div align="center">
    <video autoplay loop muted src="https://github.com/huangyangyi/TeCH/assets/7944350/f8fc55ed-9cbe-4b5f-bd1d-237396360713" type=video/mp4>
    </video>
  </div>

Homepage: https://huangyangyi.github.io/TeCH/

**Comment by alexwang2013** [comment]
> I have implemented: fill backward texture from backward image. may I submit these code?
> 
> [000_0_full.obj.zip](https://github.com/YuliangXiu/ECON/files/11862619/000_0_full.obj.zip)

Hi, could you please share the code to implement the following function?

> If an appropriately aligned back image is available, it is possible to replace the existing back normal map (which was predicted from the front image using back-branch of normal estimator) with a more detailed normal map (predicted from the back image using front-branch of normal estimator). This substitution can significantly improve the quality of the reconstruction.
