### ISSUE TITLE
AttributeError: 'SMPLX' object has no attribute 'smplx_mano_vid_dict'

### ISSUE THREAD

**Issue by jder1234** [YuliangXiu/ECON#68]
Thank you for your excellent work.

When I run the demo: 
`python -m apps.infer -cfg ./configs/econ.yaml -in_dir ./examples -out_dir ./results`

I get the following errors:
![Screenshot from 2023-06-21 16-01-39](https://github.com/YuliangXiu/ECON/assets/106365097/abb2d57d-403e-4a50-bfcf-372465c1cf3f)

Do you have any idea to fix it? @YuliangXiu

**Comment by YuliangXiu** [comment]
You could `git pull` the latest version, this issue has been fixed.
