### ISSUE TITLE
maybe we need additional argument ```--compiler=msvc```? [in ```docs/installation-windows.md```]

### ISSUE THREAD

**Issue by wanjunling168** [YuliangXiu/ECON#69]
I can only build those two libs using ```python setup.py build_ext --inplace --compiler=msvc``` if I don't call ```vcvarsall.bat``` in advance.
Cython will call Distutils, and it will just pick up ```gcc``` as C compiler when in a conda environment with ```m2w64-gcc``` installed since Conda will put its dir at the top of PATH.

May be we can add ```--compiler=msvc``` argument in the tutorial since we can only use Microsoft's ```cl.exe``` with CUDA in Windows?
Or just mention it there as a hint for those who want to reuse their existed PyTorch environment and only want to make least changes to make ECON work?

**Comment by YuliangXiu** [comment]
It is @carlosedubarreto who creates this doc. Could you please make a pull request for this, by adding the `--compiler=msvc` argument, and pointing out this hint in the tutorial as well? Thanks a lot.

**Comment by carlosedubarreto** [comment]
Very interesting I didnt know that option @wanjunling168. 👏
I actually didnt do a pull request, I made a step by step on this issue 
https://github.com/YuliangXiu/ECON/issues/16

That is linked on the windows instructions, and there I talk about starting the `vcvars64.bat`
