### ISSUE TITLE
TypeError: 'NoneType' object is not subscriptable

### ISSUE THREAD

**Issue by carlosedubarreto** [YuliangXiu/ECON#7]
Great work that you are doing, congrats on that.

I'm testing ECON on windows, and I suffered a lot to build pytorch3d, and mainly the pypoisson.
But ended up sucessfully building it, but when executing, I've got this error.

`TypeError: 'NoneType' object is not subscriptable`

The full error
`(econ) D:\AI\econ\ECON>python -m apps.infer -cfg ./configs/econ.yaml -in_dir ./examples -out_dir ./results
Resume Normal weights from  ./data/ckpt/normal.ckpt
Complete with  IF-Nets+ (Implicit)
SMPL-X estimate with  PIXIE
Dataset Size: 1
  0%|                                                                                            | 0/1 [00:00<?, ?it/s]INFO: Created TensorFlow Lite XNNPACK delegate for CPU.
Body Fitting --- normal: 0.023 | silhouette: 0.053 | joint: 0.059 | Total: 0.135| loose:0, occluded:0: 100%|█| 50/50 [0
examples\304e9c4798a8c3967de7c74c24ef2e38:   0%|                                                 | 0/1 [01:25<?, ?it/s]
Traceback (most recent call last):
  File "C:\Users\carlo\.conda\envs\econ\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\carlo\.conda\envs\econ\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "D:\AI\econ\ECON\apps\infer.py", line 422, in <module>
    verts_IF, faces_IF = ifnet_model.reconEngine.export_mesh(sdf)
  File "C:\Users\carlo\.conda\envs\econ\lib\site-packages\torch\autograd\grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "D:\AI\econ\ECON\lib\common\seg3d_lossless.py", line 619, in export_mesh
    final = occupancys[1:, 1:, 1:].contiguous()
TypeError: 'NoneType' object is not subscriptable`

![image](https://user-images.githubusercontent.com/4061130/210217501-27fcc54e-ab88-459d-9833-9bc05e76eb2e.png)

Do you have an idea of how to solve this error?
thanks a lot.

**Comment by YuliangXiu** [comment]
Here is the correct running log:

```bash
Resume Normal weights from  ./data/ckpt/normal.ckpt 
Resume MLP weights from  ./data/ckpt/ifnet.ckpt 
Complete with  SMPL-X (Explicit) 
SMPL-X estimate with  PIXIE 
Dataset Size: 1
```
I think you probably forgot to download the `ifnet.ckpt` or didn't put it under `ckpt/data`.

Also, you can also set `use_ifnet=False` in `econ.yaml`, the final results won't be quite different but with faster speed.

**Comment by carlosedubarreto** [comment]
And it worked awesomely well.

I dont know how I messed that, the ifnet.ckpt was missing and there was a differente normal.ckpt file in the folder. I replaced with the ones in econ_data and it worked.

thanks a lot!!!
![image](https://user-images.githubusercontent.com/4061130/210225651-4f0cfde6-f87c-42f9-beb0-53173e17739f.png)

**Comment by YuliangXiu** [comment]
@carlosedubarreto 

Good to know. Would you mind sharing some hints / pulling a request on *How to setup ECON in Windows?*? This will help other Windows users a lot :)

**Comment by carlosedubarreto** [comment]
sure, no problem.
I have to redo the steps I've done. The pypoisson I still dont know how I made that work (I've been trying for 3 days)

And you mean to make a pull request to add the instruction on the installation part, right?

**Comment by YuliangXiu** [comment]
Exactly, you could add a new `##Setup on Windows` section into [docs/installation.md](https://github.com/YuliangXiu/ECON/blob/master/docs/installation.md), and list your hints or share your experience here.

My personal hint to install `pypoisson` is using `gcc7`, I cannot run it successfully until change the gcc version.
