### ISSUE TITLE
render backview from image, code is here.

### ISSUE THREAD

**Issue by yuedajiong** [YuliangXiu/ECON#71]
1) ECON contruct 3d shape and render 'frontview' texture by one image, render 'backview' by normal or gray(0.50.50.5), in fact, no render.

2) I use another image for 'backview' texture, same logic with ECON frontview.   but not texture generation, no any advanced fusion, so far.

if need, mail me, or wechat: john122333.

**Comment by yuedajiong** [comment]
[back.zip](https://github.com/YuliangXiu/ECON/files/11987164/back.zip)

**Comment by YuliangXiu** [comment]
We recently released a new work, TeCH, it could produce detailed back-side surface with texture, which is consistent with the front-side.

<div align="center">
    <video autoplay loop muted src="https://github.com/huangyangyi/TeCH/assets/7944350/f8fc55ed-9cbe-4b5f-bd1d-237396360713" type=video/mp4>
    </video>
  </div>

Homepage: https://huangyangyi.github.io/TeCH/
