### ISSUE TITLE
Is this project able to work with Monoport?

### ISSUE THREAD

**Issue by sylyt62** [YuliangXiu/ECON#73]
Hey! Thanks for your great work! I got two Qs

1. Monoport is working with pifu, is it possible to switch to ICON or ECON, and remain in realtime? 

2. If I use a depth camera, anywhere from ECON could be improved with the extra could points?

Best!

**Comment by YuliangXiu** [comment]
1. Nope. MonoPort only works for implicit function. The speed bottleneck of ECON mainly lies in SMPL-X optimization and Poisson reconstruction, which could not be accelerated using MonoPort's strategy.
2. Now, `final_depth = smpl_depth (coarse) + cloth_normal (fine)`, if the depth is available, the front-view `smpl_depth` could be replaced alternatively, this will help to mitigate the issue of bending legs.
