### ISSUE TITLE
How to get human mask?

### ISSUE THREAD

**Issue by luoshuiyue** [YuliangXiu/ECON#76]
Thanks for great work! I want to ask how to get the mask to obtain the human object in the image becasue I can see very great performance. Can you share with me what method you used in this paper?

**Comment by YuliangXiu** [comment]
`rembg + Mask-RCNN`, you could check [process_image](https://github.com/YuliangXiu/ECON/blob/master/lib/common/imutils.py#L176) for more details.

**Comment by luoshuiyue** [comment]
thanks very much~

**Comment by luoshuiyue** [comment]
The original image with mask and background removed can be obtained by rembg. Why do we need Mask R CNN?

**Comment by YuliangXiu** [comment]
@luoshuiyue  This is because `rembg` can only segment the foreground (fine-level), but what we really need is instance mask, so we also use `Mask R-CNN` for instance segmentation (coarse-level).
