### ISSUE TITLE
Why the body_pose parameter of the model in the results is 21*3

### ISSUE THREAD

**Issue by ireneisme** [YuliangXiu/ECON#80]
Thanks very much for sharing this wonderful project! I am new in this field and ECON is my first try to generate an avatar from single image. After runing the code, I found the parameter of the model input is somewhat different with my understanding about SMPLX.

I have printed the shape of each variable showned below. What I am confused about is the number of body_pose. According to the paper, I think it should be 24 joints times 3 dimensions which contains 2 more joints. Can you pls exlain what are missing or what is wrong with my understanding of this question?
```
...
body_shape : torch.Size([1, 21, 3])
...
```

One more thing, could you also provide some suggestions about how to convert this to the SMPL model one? Thanks a lot!

**Comment by YuliangXiu** [comment]
Thanks for asking

`21 = 25-1(pelvis)-2(left eye, right eye)-1(jaw)`

**Comment by ireneisme** [comment]
Thanks very much! But I am still wondering how I can get the left & right eye pose parameter from the .npy file?
```
 smpl_info = {
                    "betas":
                    optimed_betas[idx].detach().cpu().unsqueeze(0),
                    "body_pose":
                    rotation_matrix_to_angle_axis(optimed_pose_mat[idx].detach()
                                                 ).cpu().unsqueeze(0),
                    "global_orient":
                    rotation_matrix_to_angle_axis(optimed_orient_mat[idx].detach()
                                                 ).cpu().unsqueeze(0),
                    "transl":
                    optimed_trans[idx].detach().cpu(),
                    "expression":
                    data["exp"][idx].cpu().unsqueeze(0),
                    "jaw_pose":
                    rotation_matrix_to_angle_axis(data["jaw_pose"][idx]).cpu().unsqueeze(0),
                    "left_hand_pose":
                    rotation_matrix_to_angle_axis(data["left_hand_pose"][idx]).cpu().unsqueeze(0),
                    "right_hand_pose":
                    rotation_matrix_to_angle_axis(data["right_hand_pose"][idx]).cpu().unsqueeze(0),
                    "scale":
                    data["scale"][idx].cpu(),
                }
```
