### ISSUE TITLE
SMPLX meshes for RenderPeople dataset.

### ISSUE THREAD

**Issue by leetcodevis13** [YuliangXiu/ECON#89]
Hi authors thanks for sharing the code base. 

Regarding the dataset, could you please share the source or codebase for fitting SMPLX to scans. Especially for render people dataset.

**Comment by YuliangXiu** [comment]
You could find the SMPL-X fits from [AGORA](https://ps.is.mpg.de/code/agora-avatars-in-geography-optimized-for-regression-analysis). 

As for the SMPL-X fitting, please check [EasyMocap](https://github.com/zju3dv/EasyMocap)
