### ISSUE TITLE
Mesh result is broken all the time

### ISSUE THREAD

**Issue by pelmentor** [YuliangXiu/ECON#9]
Hello, does anyone know If there's a fix for this? 
![image](https://user-images.githubusercontent.com/96078254/210471963-a468beeb-d0e5-4bd7-bb4f-eda19ec707bc.png)

Every result is like this... Wrecked mesh.

**Comment by alexjabka** [comment]
How do I make it whole? It's always missing parts.

**Comment by alexjabka** [comment]
Actually it's not a big deal, you can fix this with sculpting. But result is always like this or it can be improved?

**Comment by YuliangXiu** [comment]
I guess you didn't install `pypoisson` correctly, the poisson reconstruction step ([infer.py#L549](https://github.com/YuliangXiu/ECON/blob/master/apps/infer.py#L549)) will inpaint the missing parts and removing such artifacts.

But you don't need to install `pypoisson` now, I have replaced it with MeshLab's screened poisson reconstruction yesterday. You could `git pull` to get latest code.

**Comment by alexjabka** [comment]
My bad! Now it's working. Thank you.
