### ISSUE TITLE
a way to get rid of wrinkles on the side?

### ISSUE THREAD

**Issue by Subin-Kim46** [YuliangXiu/ECON#90]
Hi,

Thank you for your excellent investigation. 
I got the result of some example used demo. It was a good result. 
I want to ask you a few questions for a better outcome. 
I want to get a smooth mash. Any tips for further development? Is there a way to get rid of wrinkles on the side?

![image](https://github.com/YuliangXiu/ECON/assets/76643618/1759d628-5dc6-4d19-8491-a6ee50d838b2)

**Comment by YuliangXiu** [comment]
These kinds of artifacts mainly come from the wrong boundary triangles, which are optimized (via d-BiNI) from the wrongly estimated normal boundary. You could do **erode** operation on the normal maps, to shrink the normal boundary a bit, and then do mesh completion, I guess this will help.

**Comment by Subin-Kim46** [comment]
Can you tell me where the hyperparameters of these process?
Thank you so much if you let me know which part to fix

**Comment by YuliangXiu** [comment]
You can start from [here](https://github.com/YuliangXiu/ECON/blob/master/lib/common/BNI_utils.py#L668), **erode** the depth maps rather than normal maps.
