### ISSUE TITLE
How to evaluate on custom datasets?

### ISSUE THREAD

**Issue by wszswppx** [YuliangXiu/ECON#96]
Thanks for your outstanding job.

I want to **evaluate ECON on other dataset, or at  least on other items in CAPE**, rather than just on the provided list in [testing.md and pose.txt](https://github.com/YuliangXiu/ECON/blob/master/docs/testing.md#testing-data) . 

Now all I have is some `.obj` files of clothed human.

My question is   
1. Is it necessary to prepare smpl(-x) GT first for each item? If so, how can I get them?
2. Is it necessary to build a `xxx_3views` folder for my data, just like `cape_3views` for `cape`? If so, how can I make such directory and related data like `calib`, `mask`, etc?

Thanks a lot.

**Comment by YuliangXiu** [comment]
1. YES. Because SMPL-X is used in the reconstruction process, maybe you can try on [EasyMocap](https://github.com/zju3dv/EasyMocap).
2. YES. Just follow the rendering scripts in [ICON](https://github.com/YuliangXiu/ICON/blob/master/docs/dataset.md)
