### ISSUE TITLE
段错误 (核心已转储)

### ISSUE THREAD

**Issue by QUANmoxiansheng** [YuliangXiu/ECON#97]
修老师你好，我在运行ECON的时候改成IF的方式就会出现“段错误 (核心已转储)”，如果不用IF又能正常使用，这是我配置的问题还是我电脑的问题？

**Comment by QUANmoxiansheng** [comment]
![image](https://github.com/YuliangXiu/ECON/assets/74361545/8582115a-cb26-42dc-b160-e3bd54a6529f)

**Comment by QUANmoxiansheng** [comment]
> I strongly suggest utilizing line-by-line debugging using `ipdb`. A segmentation fault can arise from various factors.
Ok, thanks for your reply. I'll try it.

**Comment by glorioushonor** [comment]
> I strongly suggest utilizing line-by-line debugging using `ipdb`. A segmentation fault can arise from various factors.

![b76268a967ebcc5844692314797f7f6](https://github.com/YuliangXiu/ECON/assets/120625228/9d6bd015-3e3e-4ca7-8ffc-f2cb1a156b1d)
I encountered the same issue and  utilized line-by-line debugging using ipdb. Eventually, I found that the problem lies in the PyTorch3D marching cubes function. I confirmed that I have installed PyTorch3D version 0.7.1, but I haven't resolved the issue yet. Do you have some requirements，please?

**Comment by MIkeR794** [comment]
I have the same problem. Have you solved it？

**Comment by QUANmoxiansheng** [comment]
> > I strongly suggest utilizing line-by-line debugging using `ipdb`. A segmentation fault can arise from various factors.
> 
> ![b76268a967ebcc5844692314797f7f6](https://private-user-images.githubusercontent.com/120625228/285487804-9d6bd015-3e3e-4ca7-8ffc-f2cb1a156b1d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIxMjkwMDIsIm5iZiI6MTcwMjEyODcwMiwicGF0aCI6Ii8xMjA2MjUyMjgvMjg1NDg3ODA0LTlkNmJkMDE1LTNlM2UtNGNhNy04ZmZjLWYyY2IxYTE1NmIxZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIwOVQxMzMxNDJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mMDg5OTA1NDAxYTIyZDkwNzE5MTA3YTgxMjBlNjUzOGQ2OTZhM2IxNjMxYmJjYmE0MzEyODBkM2ZhNjdiZTNhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Pn_P0UWzENa24ih6Ob_n147noI9yEaOgxwiC-JtPN-E) I encountered the same issue and utilized line-by-line debugging using ipdb. Eventually, I found that the problem lies in the PyTorch3D marching cubes function. I confirmed that I have installed PyTorch3D version 0.7.1, but I haven't resolved the issue yet. Do you have some requirements，please?

This is probably because Pytorch 3D0.7.1 is not supported and try a new version.

**Comment by MIkeR794** [comment]
@QUANmoxiansheng thanks,I try pytorch3d version 0.7.2 and it works.
