### ISSUE TITLE
Question about training

### ISSUE THREAD

**Issue by QUANmoxiansheng** [YuliangXiu/ECON#98]
I wanted to retrain your ECON work, but I didn't see the steps for training. Could you please tell me what I should do? Or is the training procedure the same as the ICON's?

**Comment by YuliangXiu** [comment]
Please check the [dev branch](https://github.com/YuliangXiu/ECON/blob/dev/apps/train-IF-geo.py), which contains the training code (without organization, so a bit dirty).
